services:
  - type: pserv
    name: mail
    env: docker
    dockerfilePath: ./docker-smtp/Dockerfile
    region: frankfurt
    plan: starter
  - type: pserv
    name: plausible_events_db
    env: docker
    dockerfilePath: ./clickhouse-server/Dockerfile
    region: frankfurt
    plan: starter
  - type: web
    name: plausible
    env: docker
    dockerfilePath: ./plausible-analytics/Dockerfile
    dockerCommand: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    envVars:
      - key: BASE_URL
        value: https://plausible.cryptr.co
      - key: ADMIN_USER_NAME
        value: admin
      - key: ADMIN_USER_EMAIL
        value: thibaud@cryptr.co
      - key: ADMIN_USER_PWD
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: plausible_db
          type: pserv
          property: connectionString
      - key: MAIL_URL
        fromService:
          name: mail
          type: pserv
          property: connectionString
      - key: EVENTS_URL
        fromService:
          name: plausible_events_db
          type: pserv
          property: connectionString
databases:
  - name: plausible_db
    databaseName: plausible_db
    ipAllowList: []
    postgresMajorVersion: 12
    plan: starter
    region: frankfurt