services:
  # - type: pserv
  #   name: mail
  #   env: docker
  #   dockerfilePath: ./docker-smtp/Dockerfile
  #   region: frankfurt
  #   plan: starter
  - type: pserv
    name: plausible_events_db
    env: docker
    dockerfilePath: ./clickhouse-server/Dockerfile
    region: frankfurt
    plan: starter plus
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 1
  - type: web
    name: cryptr-plausible
    env: docker
    repo: https://github.com/plausible/analytics.git
    plan: starter plus
    envVars:
      - key: BASE_URL
        value: https://plausible.cryptr.co
      - key: ADMIN_USER_NAME
        value: admin
      - key: ADMIN_USER_EMAIL
        value: thibaud@cryptr.co
      - key: POSTMARK_API_KEY
        sync: false
      - key: ADMIN_USER_PWD
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: plausible_db
          type: pserv
          property: connectionString
      - key: CLICKHOUSE_DATABASE_URL
        fromService:
          name: plausible_events_db
          type: pserv
          property: host
databases:
  - name: plausible_db
    databaseName: plausible_db
    ipAllowList: []
    postgresMajorVersion: 12
    plan: starter plus
    region: frankfurt